package:
  name: ros-humble-ament-cmake-gtest
  version: 1.3.2
source:
  git_url: https://github.com/ros2-gbp/ament_cmake-release.git
  git_rev: release/humble/ament_cmake_gtest/1.3.2-1
  folder: ros-humble-ament-cmake-gtest/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - gtest
    - python
    - ros-humble-ament-cmake-core
    - ros-humble-ament-cmake-test
    - ros-humble-gtest-vendor
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - gtest
    - python
    - ros-humble-ament-cmake-test
    - ros-humble-gtest-vendor
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
