package:
  name: ros-humble-ament-uncrustify
  version: 0.12.4
source:
  git_url: https://github.com/ros2-gbp/ament_lint-release.git
  git_rev: release/humble/ament_uncrustify/0.12.4-1
  folder: ros-humble-ament-uncrustify/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pytest
    - python
    - ros-humble-ament-copyright
    - ros-humble-ament-flake8
    - ros-humble-ament-pep257
    - ros-humble-ament-pycodestyle
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - setuptools
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-uncrustify-vendor
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
